# Generated by Django 2.2.7 on 2019-11-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('middle_initial', models.CharField(default='', max_length=1)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('ssn', models.IntegerField(default=0)),
                ('dob', models.DateField()),
                ('pob', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('city', models.CharField(default='', max_length=64)),
                ('division', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.CharField(default='', max_length=10)),
                ('position', models.CharField(choices=[('Forward', (('C', 'Center'), ('RW', 'Right Wing'), ('LW', 'Left Wing'))), ('Defense', (('RD', 'Right Defense'), ('LD', 'Left Defense'))), ('Goalie', 'Goalie')], default='', max_length=20)),
                ('stick_orientation', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='league.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Person')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
    ]
