# Generated by Django 2.2.7 on 2019-11-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=64)),
                ('ssn', models.IntegerField(max_length=9)),
                ('dob', models.DateField()),
                ('pob', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
