# Generated by Django 2.2.7 on 2019-11-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20191120_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
