# Generated by Django 2.2.7 on 2019-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='t1goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='t2goals',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
