# Generated by Django 2.2.7 on 2019-11-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stick_orientation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight',
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.Person'),
        ),
    ]
