# Generated by Django 2.2.7 on 2019-11-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20191121_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
    ]
