# Generated by Django 2.2.7 on 2019-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20191122_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.CharField(default='', max_length=9),
        ),
    ]
