# Generated by Django 2.2.7 on 2019-11-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20191121_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Person'),
        ),
    ]
