# Generated by Django 2.2.7 on 2019-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20191122_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='', max_length=5),
        ),
    ]
