# Generated by Django 2.2.7 on 2019-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20191121_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='stick_orientation',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_initial',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='pob',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.IntegerField(default=0),
        ),
    ]
