# Generated by Django 2.2.7 on 2019-11-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_coach_manager_referee_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
            preserve_default=False,
        ),
    ]
