# Generated by Django 2.2.7 on 2019-11-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20191121_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='team',
        ),
    ]
