# Generated by Django 2.2.7 on 2019-11-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20191121_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Person'),
        ),
    ]
