# Generated by Django 2.2.7 on 2019-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20191121_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Forward', (('C', 'Center'), ('RW', 'Right Wing'), ('LW', 'Left Wing'))), ('Defense', (('RD', 'Right Defense'), ('LD', 'Left Defense'))), ('Goalie', 'Goalie')], default='', max_length=20),
        ),
    ]
