# Generated by Django 2.2.7 on 2019-11-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20191121_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stick_orientation',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=5),
        ),
    ]
