# Generated by Django 2.2.7 on 2019-11-22 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.CharField(default='', max_length=10)),
                ('position', models.CharField(choices=[('Forward', (('C', 'Center'), ('RW', 'Right Wing'), ('LW', 'Left Wing'))), ('Defense', (('RD', 'Right Defense'), ('LD', 'Left Defense'))), ('Goalie', 'Goalie')], default='', max_length=20)),
                ('stick_orientation', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
    ]
