# Generated by Django 2.2.7 on 2019-11-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
