# Generated by Django 2.2.7 on 2019-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='toi',
            field=models.CharField(default='', max_length=15),
        ),
    ]
