# Generated by Django 2.2.7 on 2019-11-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_person_ssn'),
        ('players', '0006_auto_20191123_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('head coach', 'head coach'), ('assitant coach', 'assitant coach')], default='', max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='persons.Person')),
            ],
        ),
    ]
