# Generated by Django 2.2.7 on 2019-12-02 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20191202_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assist',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='hits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(260)]),
        ),
    ]
