# Generated by Django 2.2.7 on 2019-12-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20191202_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='referee',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
    ]
