# Generated by Django 2.2.7 on 2019-12-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20191204_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', unique=True),
        ),
    ]
