# Generated by Django 2.2.7 on 2019-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='position',
            field=models.CharField(choices=[('head coach', 'head coach'), ('assistant coach', 'assistant coach')], default='', max_length=20),
        ),
    ]
