# Generated by Django 2.2.7 on 2019-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('division', models.CharField(choices=[('good', 'good'), ('bad', 'bad')], default='', max_length=4)),
            ],
        ),
    ]
