# Generated by Django 2.2.7 on 2019-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_team'),
        ('teams', '0002_auto_20191123_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(to='players.Player'),
        ),
    ]
