# Generated by Django 2.2.7 on 2019-11-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20191123_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='player',
            new_name='players',
        ),
    ]
