# Generated by Django 2.2.7 on 2019-12-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20191205_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamScore',
        ),
    ]
