# Generated by Django 2.2.7 on 2019-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('teams', '0008_auto_20191205_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(to='coaches.Coach'),
        ),
    ]
