# Generated by Django 2.2.7 on 2019-12-05 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20191205_0719'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='t1',
        ),
        migrations.AddField(
            model_name='game',
            name='homeScore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_score', to='teams.TeamScore'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitingScore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team_score', to='teams.TeamScore'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitingTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
