# Generated by Django 2.2.7 on 2019-11-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20191123_0015'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='t2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='teams.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='teams.Team'),
        ),
    ]
