# Generated by Django 2.2.7 on 2019-11-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191123_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='t1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='t2Score',
            field=models.IntegerField(default=0),
        ),
    ]
