# Generated by Django 2.2.7 on 2019-11-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='games.Game'),
        ),
    ]
