# Generated by Django 2.2.7 on 2019-11-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20191123_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
