# Generated by Django 2.2.7 on 2019-11-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20191123_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='t1Score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='t2Score',
        ),
    ]
