# Generated by Django 2.2.7 on 2019-12-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20191124_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='t1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='t2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
        migrations.DeleteModel(
            name='GameDetail',
        ),
    ]
