# Generated by Django 2.2.7 on 2019-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('middle_initial', models.CharField(default='', max_length=1)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('ssn', models.CharField(default='', max_length=9)),
                ('dob', models.DateField()),
                ('pob', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
